name: "nats-client-action"
author: "onichandame"
description: "Github action to test a NATS server/cluster"
branding:
  color: "blue"
inputs:
  servers:
    description: "The servers requiring testing. e.g. 'nats://localhost:4222 nats://localhost:4223'"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
