name: Test
on: [push]
jobs:
  test-servers:
    runs-on: ubuntu-latest
    name: Test individual servers

    steps:
      - name: Create Nats server
        run: sudo docker run -d -p 4222:4222 nats && sudo docker run -d -p 4223:4222 nats

      - name: connect to server
        uses: onichandame/nats-client-action@master
        with:
          servers: "nats://localhost:4222 nats://localhost:4223"
  test-cluster:
    runs-on: ubuntu-latest
    name: Test cluster

    steps:
      - name: Create Nats server
        run: sudo docker run -d -p 4222:4222 --name master --cluster nats://0.0.0.0:6222 nats && sudo docker run -d -p 4223:4222 --cluster nats://0.0.0.0:6222 --routes=nats://master:6222 nats

      - name: connect to server
        uses: onichandame/nats-client-action@master
        with:
          servers: "nats://localhost:4222 nats://localhost:4223"
          cluster: "true"
