name: Test
on: [push]
jobs:
  test-nats-action:
    runs-on: ubuntu-latest
    name: Test NATS action

    steps:
      - name: Create Nats server
        run: sudo docker run -d -p 4222:4222 nats

      - name: connect to server
        uses: onichandame/nats-client-action@master
        with:
          servers: "nats://localhost:4222"
